name: Aternos AFK Bot
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *" # 5 saatte bir yeniden başlar (GitHub Actions sınırı için)
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Node.js kurulumu
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Bağımlılıkları yükle
        run: npm install
      - name: Botu başlat
        run: node index.js
